
import { GraphData, Node, Edge } from '../types';

/**
 * Generates a .cursorrules file content based on the graph analysis.
 * It identifies high-level architectural boundaries and suggests constraints.
 */
export const generateCursorRules = (data: GraphData, activeModule: string | null): string => {
    const lines: string[] = [];

    lines.push(`# Cursor Rules for ${activeModule || 'Root Codebase'}`);
    lines.push(`# Generated by Codebase Visualizer`);
    lines.push(``);
    lines.push(`You are an expert AI assistant working in this codebase.`);
    lines.push(`Respect the following architectural boundaries and project structure.`);
    lines.push(``);

    // 1. Module Structure
    lines.push(`## Module Structure`);

    // Identify top-level modules
    const modules = new Set<string>();
    data.nodes.forEach(n => {
        if (n.modulePath && n.modulePath[0]) modules.add(n.modulePath[0]);
    });

    lines.push(`The codebase is organized into the following high-level modules:`);
    modules.forEach(m => lines.push(`- **${m}**: Primary domain.`));
    lines.push(``);

    // 2. Dependency Rules (Inferred)
    // Find edges between modules to see what IS allowed (description of current state)
    // Or we could define strict rules. For now, let's describe valid flows.
    lines.push(`## Dependency Flow`);

    // Check flow between 'Frontend' and 'Backend' if they exist
    const hasFrontend = modules.has('Frontend');
    const hasBackend = modules.has('Backend');

    if (hasFrontend && hasBackend) {
        lines.push(`- **Frontend** code typically imports from **Backend** API/Types, but essentially they are distinct.`);
        lines.push(`- Do NOT import server-side logic (Models, Services) into Client Components.`);
    }

    // 3. Tech Stack Context
    // Guess based on file extensions or node types
    const types = new Set(data.nodes.map(n => n.type));
    lines.push(`## Technology Stack Hints`);
    if (types.has('component')) lines.push(`- This appears to be a React/Component-based project.`);
    if (types.has('model') || types.has('schema')) lines.push(`- Backend includes Data Models/Schemas.`);
    lines.push(``);

    // 4. Best Practices
    lines.push(`## General Guidelines`);
    lines.push(`- Keep modules cohesive.`);
    lines.push(`- Avoid circular dependencies between '${Array.from(modules).slice(0, 3).join("', '")}'.`);

    return lines.join('\n');
};
